// Code generated by "stringer -type=ResponseCode -linecomment -output=models_string.go"; DO NOT EDIT.

package daraja

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownResponseCode - -1]
	_ = x[SuccessSubmission-1]
	_ = x[InvalidAccountReference-2]
	_ = x[EmptyAccountReference-3]
	_ = x[CheckSuccess-4]
	_ = x[InvalidReceiverIdentifierType-5]
	_ = x[InvalidAccessToken-6]
	_ = x[BadRequest-7]
	_ = x[InvalidRequestPayload-8]
	_ = x[InvalidGrantType-9]
	_ = x[InvalidAuthType-10]
	_ = x[InvalidAuthHeader-11]
	_ = x[ResourceNotFound-12]
	_ = x[SubscriberLock-13]
	_ = x[ServiceTemporarilyUnavailable-14]
	_ = x[SpikeArrestViolation-15]
	_ = x[QuotaViolation-16]
	_ = x[InternalServerError-17]
}

const (
	_ResponseCode_name_0 = "9999"
	_ResponseCode_name_1 = "02310054000400.002.02400.003.01400.003.02400.002.05400.008.02400.008.01404.001.04404.003.01500.001.1001500.002.1001500.003.02500.003.03500.003.1001"
)

var (
	_ResponseCode_index_1 = [...]uint8{0, 1, 3, 7, 11, 21, 31, 41, 51, 61, 71, 81, 91, 103, 115, 125, 135, 147}
)

func (i ResponseCode) String() string {
	switch {
	case i == -1:
		return _ResponseCode_name_0
	case 1 <= i && i <= 17:
		i -= 1
		return _ResponseCode_name_1[_ResponseCode_index_1[i]:_ResponseCode_index_1[i+1]]
	default:
		return "ResponseCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
