CREATE TABLE IF NOT EXISTS public."payment_requests"
(
    "id"                         uuid,
    "payment_id"                 text,
    "client_transaction_id"      text,
    "idempotency_id"             text,
    "payment_reference"          text,
    "amount"                     text,
    "currency"                   text,
    "source_account_number"      text,
    "external_account_number"    text,
    "beneficiary_account_number" text,
    "description"                text,
    "bank"                       text,
    "type"                       text,
    "status"                     text,
    "created_at"                 timestamp,
    "updated_at"                 timestamp,
    PRIMARY KEY ("id"),
    CONSTRAINT "uni_payment_requests_payment_id" UNIQUE ("payment_id"),
    CONSTRAINT "uni_payment_requests_client_transaction_id" UNIQUE ("client_transaction_id"),
    CONSTRAINT "chk_payment_requests_idempotency_id" CHECK (idempotency_id <> ''),
    CONSTRAINT "chk_payment_requests_payment_id" CHECK (payment_id <> ''),
    CONSTRAINT "chk_payment_requests_client_transaction_id" CHECK (client_transaction_id <> ''),
    CONSTRAINT "chk_payment_requests_payment_reference" CHECK (payment_reference <> '')
);